FROM node:14.17.6-alpine as build

WORKDIR /app

ENV NODE_ENV=production
ARG PUBLIC_URL
ARG REACT_APP_BASE

COPY package*.json ./

RUN npm ci --silent \
    && npm install react-scripts@3.4.1 -g --silent

COPY . ./

RUN npm run build

# production environment

FROM nginx:stable-alpine

COPY --from=build /app/build  /var/www/html/static/

COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]

