openapi: '3.0.0'
info:
  title: 'Betti API'
  version: '0.0.1'
  description: 'Betti API docs'
servers:
  - url: 'http://betti.kr:8000'
    description: 'Development server'
  - url: 'http://betti.kr:8001'
    description: 'Production server'
basePath: '/'
path: /documentation/v2/api-docs
