openapi: '3.0.0'
info:
  title: 'Betti API'
  version: '0.0.1'
  description: 'Betti API docs'
servers:
  - url: 'http://ec2-3-34-2-242.ap-northeast-2.compute.amazonaws.com:8000'
    description: 'Development server'
  - url: 'http://ec2-3-34-2-242.ap-northeast-2.compute.amazonaws.com:8001'
    description: 'Production server'
basePath: '/api'
